{
 "title": "Go App Metrics",
 "panels": [
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{path}} {{method}}" }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])"
    }
   ]
  }
 ]
}